### ISSUE TITLE
This is not front end packing

### ISSUE THREAD

**Issue by Jeremiahgibson** [sio2boss/pack#1]
This is a javascript wrapper for linux commands. The best this would do is allow front end users to zip files that are already located in the backend.

**Comment by sio2boss** [comment]
Right, `pack` is a wrapper for linux commands to compress files.  Its the opposite abstraction to https://github.com/sio2boss/unpack.  Not sure what you are asking.

**Comment by Jeremiahgibson** [comment]
Yeah sorry. The description for this repo says front end.  Maybe update it to say "this is a node package wrapping Linux cli commands for compression algorithms I.E zip, gz, etc.

**Comment by sio2boss** [comment]
ah, that makes sense.  github description updated.  Thanks for the feedback
